version: '3.9'

services:
  carbon-gateway:
    image: nginx
    restart: unless-stopped
    container_name: carbon-gateway
    ports:
      - 6010:80
      - 6011:443
    networks:
      carbon-network:
        ipv4_address: 182.39.0.2
        aliases:
          - carbon.local.com
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway/certs:/etc/nginx/certs

  carbon-database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin-password
      - POSTGRES_DB=carbonDB
    container_name: carbon-database
    networks:
      carbon-network:
        ipv4_address: 182.39.0.3
        aliases:
          - carbon.database.local.com
    ports:
      - '5432:5432'

  carbon-api:
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    image: carbon-api
    ports:
      - 6004:3000
    networks:
      carbon-network:
        ipv4_address: 182.39.0.4
        aliases:
          - carbon.api.local.com
    restart: unless-stopped
    depends_on:
      - carbon-gateway
      - carbon-database
    volumes:
      - .:/app
      - /app/node_modules
    container_name: carbon-api
    command: npm run start:dev

volumes:
  cache:
    driver: local

networks:
  carbon-network:
    ipam:
      driver: default
      config:
        - subnet: 182.39.0.0/24
